import { Injectable, NotFoundException } from '@nestjs/common';
import { StudioRole } from '@playmorrow/database';
import type { Prisma } from '@playmorrow/database';

import { assertStudioAccess } from '../common/studio-permissions';
import { PrismaService } from '../prisma/prisma.service';
import type { UpsertPressKitDto } from './dto/upsert-press-kit.dto';
import { AuditLogService } from '../audit-log/audit-log.service';
import { FeedEngineService } from '../feed/feed-events.service';

export interface PressKitResponse {
  id: string;
  headline: string | null;
  factSheet: Prisma.JsonValue;
  contactEmail: string | null;
  downloadUrl: string | null;
  isAutoGenerated: boolean;
  game: {
    id: string;
    title: string;
    slug: string;
    tagline: string | null;
    status: string;
    releaseDate: string | null;
    expectedReleaseText: string | null;
    priceCents: number | null;
    currency: string | null;
    isFree: boolean;
    coverUrl: string | null;
    bannerUrl: string | null;
  };
  studio: { id: string; name: string; slug: string; websiteUrl: string | null };
  media: { id: string; type: string; url: string; caption: string | null; position: number }[];
  platformLinks: { id: string; platform: string; url: string; label: string | null }[];
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

const GAME_INCLUDE_FOR_PRESS_KIT = {
  studio: { select: { id: true, name: true, slug: true, websiteUrl: true } },
  media: { orderBy: { position: 'asc' as const } },
  platformLinks: { orderBy: { position: 'asc' as const } },
  tags: { include: { tag: true } },
} satisfies Prisma.GameInclude;

@Injectable()
export class PressKitsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly auditLog: AuditLogService,
    private readonly feedEngine: FeedEngineService,
  ) {}

  async upsert(userId: string, gameSlug: string, dto: UpsertPressKitDto): Promise<PressKitResponse> {
    const game = await this.prisma.game.findUnique({
      where: { slug: gameSlug.toLowerCase() },
      include: { studio: { include: { members: true } } },
    });
    if (!game) {
      throw new NotFoundException('Game not found');
    }

    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException('User not found');
    }

    assertStudioAccess({ id: userId, role: user.role }, game.studio.members, [StudioRole.OWNER, StudioRole.ADMIN, StudioRole.MODERATOR, StudioRole.MEMBER]);

    const updateData: Record<string, unknown> = {
      headline: dto.headline,
      isAutoGenerated: false,
    };
    if (dto.factSheet !== undefined) updateData.factSheet = dto.factSheet;
    if (dto.contactEmail !== undefined) updateData.contactEmail = dto.contactEmail;
    if (dto.downloadUrl !== undefined) updateData.downloadUrl = dto.downloadUrl;

    await this.prisma.pressKit.upsert({
      where: { gameId: game.id },
      create: { ...updateData, gameId: game.id } as Prisma.PressKitUncheckedCreateInput,
      update: updateData as Prisma.PressKitUncheckedUpdateInput,
    });

    await this.auditLog.log({
      studioId: game.studioId,
      actorId: userId,
      action: 'PRESS_KIT_UPSERTED',
      targetType: 'PRESS_KIT',
      targetId: game.id,
    });

    this.feedEngine.emit('PRESS_KIT_UPDATED', {
      studioId: game.studioId,
      gameId: game.id,
      actorId: userId,
      payload: { title: game.title },
    }).catch((err) => logger.error({ err }));

    return this.findByGameSlug(gameSlug);
  }

  async findByGameSlug(gameSlug: string): Promise<PressKitResponse> {
    const game = await this.prisma.game.findUnique({
      where: { slug: gameSlug.toLowerCase() },
      include: GAME_INCLUDE_FOR_PRESS_KIT,
    });
    if (!game) {
      throw new NotFoundException('Game not found');
    }

    const pressKit = await this.prisma.pressKit.findUnique({
      where: { gameId: game.id },
    });

    if (!pressKit) {
      throw new NotFoundException('Press kit not found for this game');
    }

    return this.toResponse(pressKit, game);
  }

  private toResponse(
    pressKit: {
      id: string;
      headline: string | null;
      factSheet: Prisma.JsonValue;
      contactEmail: string | null;
      downloadUrl: string | null;
      isAutoGenerated: boolean;
      createdAt: Date;
      updatedAt: Date;
    },
    game: {
      id: string;
      title: string;
      slug: string;
      tagline: string | null;
      status: string;
      releaseDate: Date | null;
      expectedReleaseText: string | null;
      priceCents: number | null;
      currency: string | null;
      isFree: boolean;
      coverUrl: string | null;
      bannerUrl: string | null;
      studio: { id: string; name: string; slug: string; websiteUrl: string | null };
      media: { id: string; type: string; url: string; caption: string | null; position: number }[];
      platformLinks: { id: string; kind: string; url: string; label: string | null; position: number }[];
      tags: { tag: { slug: string; name: string; kind: string | null } }[];
    },
  ) {
    return {
      id: pressKit.id,
      headline: pressKit.headline,
      factSheet: pressKit.factSheet,
      contactEmail: pressKit.contactEmail,
      downloadUrl: pressKit.downloadUrl,
      isAutoGenerated: pressKit.isAutoGenerated,
      game: {
        id: game.id,
        title: game.title,
        slug: game.slug,
        tagline: game.tagline,
        status: game.status,
        releaseDate: game.releaseDate?.toISOString() ?? null,
        expectedReleaseText: game.expectedReleaseText,
        priceCents: game.priceCents,
        currency: game.currency,
        isFree: game.isFree,
        coverUrl: game.coverUrl,
        bannerUrl: game.bannerUrl,
      },
      studio: game.studio,
      media: game.media,
      platformLinks: game.platformLinks.map((pl) => ({
        id: pl.id,
        platform: pl.kind,
        url: pl.url,
        label: pl.label,
      })),
      tags: game.tags.map((gt) => gt.tag.slug),
      createdAt: pressKit.createdAt.toISOString(),
      updatedAt: pressKit.updatedAt.toISOString(),
    };
  }
}
