const BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api';

export class ApiError extends Error {
  status: number;
  body: unknown;

  constructor(status: number, body: unknown) {
    super(`API ${status}: ${JSON.stringify(body).slice(0, 200)}`);
    this.name = 'ApiError';
    this.status = status;
    this.body = body;
  }
}

async function request<T>(
  path: string,
  options: { method?: string; body?: unknown; token?: string } = {},
): Promise<T> {
  const { method = 'GET', body, token } = options;

  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;

  const res = await fetch(`${BASE_URL}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!res.ok) {
    const errBody = await res.json().catch(() => ({ message: res.statusText }));
    throw new ApiError(res.status, errBody);
  }

  return res.json() as Promise<T>;
}

export const api = {
  get: <T>(path: string, token?: string) => request<T>(path, { token }),
  post: <T>(path: string, body?: unknown, token?: string) =>
    request<T>(path, { method: 'POST', body, token }),
  put: <T>(path: string, body?: unknown, token?: string) =>
    request<T>(path, { method: 'PUT', body, token }),
  patch: <T>(path: string, body?: unknown, token?: string) =>
    request<T>(path, { method: 'PATCH', body, token }),
  delete: <T>(path: string, token?: string) => request<T>(path, { method: 'DELETE', token }),
};

// ── Response types (matching backend shapes) ────────────────────────────

export interface Paginated<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

export interface StudioSummary {
  id: string;
  name: string;
  slug: string;
  logoUrl: string | null;
}

export interface GameSummary {
  id: string;
  title: string;
  slug: string;
  coverUrl: string | null;
  studio: StudioSummary;
}

export interface Studio {
  id: string;
  name: string;
  slug: string;
  tagline: string | null;
  description: string | null;
  logoUrl: string | null;
  bannerUrl: string | null;
  websiteUrl: string | null;
  location: string | null;
  foundedYear: number | null;
  isVerified: boolean;
  membersCount: number;
  gamesCount: number;
  followersCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface Game {
  id: string;
  title: string;
  slug: string;
  tagline: string | null;
  description: string | null;
  status: string;
  releaseDate: string | null;
  expectedReleaseText: string | null;
  priceCents: number | null;
  currency: string | null;
  isFree: boolean;
  coverUrl: string | null;
  bannerUrl: string | null;
  isPublished: boolean;
  followersCount: number;
  studio: StudioSummary;
  media: { id: string; type: string; url: string; caption: string | null; position: number }[];
  platformLinks: { id: string; platform: string; url: string; label: string | null }[];
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Devlog {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  body: string;
  coverUrl: string | null;
  isPublished: boolean;
  publishedAt: string | null;
  game: { id: string; title: string; slug: string };
  studio: { id: string };
  author: { id: string; username: string; displayName: string; avatarUrl: string | null };
  createdAt: string;
  updatedAt: string;
}

export interface RoadmapItem {
  id: string;
  title: string;
  description: string | null;
  status: string;
  targetDate: string | null;
  position: number;
  game: { id: string; title: string; slug: string };
  studio: { id: string; name: string; slug: string };
  createdAt: string;
  updatedAt: string;
}

export interface PressKit {
  id: string;
  headline: string | null;
  factSheet: unknown;
  contactEmail: string | null;
  downloadUrl: string | null;
  isAutoGenerated: boolean;
  game: {
    id: string;
    title: string;
    slug: string;
    tagline: string | null;
    status: string;
    releaseDate: string | null;
    expectedReleaseText: string | null;
    priceCents: number | null;
    currency: string | null;
    isFree: boolean;
    coverUrl: string | null;
    bannerUrl: string | null;
  };
  studio: StudioSummary;
  media: { id: string; type: string; url: string; caption: string | null; position: number }[];
  platformLinks: { id: string; platform: string; url: string; label: string | null }[];
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

export interface FeedItem {
  id: string;
  type: 'DEVLOG' | 'ROADMAP_ITEM';
  createdAt: string;
  publishedAt: string | null;
  title: string;
  summary: string;
  status?: string;
  targetDate?: string | null;
  game: { id: string; title: string; slug: string; coverUrl: string | null };
  studio: { id: string; name: string; slug: string; logoUrl: string | null };
  target: { kind: 'DEVLOG' | 'ROADMAP_ITEM'; id: string };
}

export interface Comment {
  id: string;
  body: string | null;
  parentId: string | null;
  isDeleted?: boolean;
  deletedAt: string | null;
  author: { id: string; username: string; displayName: string; avatarUrl: string | null };
  createdAt: string;
  updatedAt: string;
}

export interface ReactionStatus {
  targetType: 'DEVLOG' | 'COMMENT';
  targetId: string;
  counts: { LIKE: number; LOVE: number; HYPE: number; INSIGHTFUL: number };
  viewerReactions: string[];
}

export interface StudioWithMembers extends Studio {
  members: {
    id: string;
    role: string;
    title: string | null;
    user: { id: string; username: string; displayName: string; avatarUrl: string | null };
  }[];
}
