import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Idempotent seed: safe to run repeatedly. Creates a handful of tags and one
 * fully-formed demo studio + game so the UI has something real to render.
 */
async function main() {
  console.log('🌱  Seeding Playmorrow…');

  // ── Tags ────────────────────────────────────────────────────────────────
  const tags = [
    { slug: 'roguelike', name: 'Roguelike', kind: 'genre' },
    { slug: 'metroidvania', name: 'Metroidvania', kind: 'genre' },
    { slug: 'cozy', name: 'Cozy', kind: 'mood' },
    { slug: 'pixel-art', name: 'Pixel Art', kind: 'feature' },
    { slug: 'narrative', name: 'Narrative', kind: 'genre' },
    { slug: 'multiplayer', name: 'Multiplayer', kind: 'feature' },
  ];
  for (const tag of tags) {
    await prisma.tag.upsert({ where: { slug: tag.slug }, update: tag, create: tag });
  }

  // ── Demo creator ──────────────────────────────────────────────────────────
  const dev = await prisma.user.upsert({
    where: { email: 'dev@playmorrow.example' },
    update: {},
    create: {
      email: 'dev@playmorrow.example',
      username: 'auroradev',
      displayName: 'Aurora Dev',
      // Placeholder only — real auth will hash credentials. Not a usable login.
      passwordHash: 'seed-placeholder-not-a-real-hash',
      role: 'PLAYER',
      bio: 'Solo developer building small worlds.',
      isVerified: true,
    },
  });

  // ── Demo studio ─────────────────────────────────────────────────────────
  const studio = await prisma.studio.upsert({
    where: { slug: 'aurora-works' },
    update: {},
    create: {
      slug: 'aurora-works',
      name: 'Aurora Works',
      tagline: 'Tiny worlds, big feelings.',
      description: 'A one-person studio crafting cozy, narrative-driven games.',
      location: 'Lisbon, Portugal',
      foundedYear: 2024,
      isVerified: true,
      members: {
        create: { userId: dev.id, role: 'OWNER', title: 'Founder & Developer' },
      },
    },
  });

  // ── Demo game ─────────────────────────────────────────────────────────────
  const game = await prisma.game.upsert({
    where: { slug: 'lanternfall' },
    update: {},
    create: {
      slug: 'lanternfall',
      studioId: studio.id,
      title: 'Lanternfall',
      tagline: 'Light the way home in a world that forgot the sun.',
      description:
        'A hand-painted exploration game about rekindling lanterns across a quiet, drifting archipelago.',
      status: 'IN_DEVELOPMENT',
      expectedReleaseText: 'Q4 2026',
      isFree: false,
      priceCents: 1999,
      isPublished: true,
      tags: {
        create: [
          { tag: { connect: { slug: 'cozy' } } },
          { tag: { connect: { slug: 'narrative' } } },
          { tag: { connect: { slug: 'pixel-art' } } },
        ],
      },
      platformLinks: {
        create: [
          { kind: 'STEAM', url: 'https://store.steampowered.com/', label: 'Wishlist on Steam' },
          { kind: 'DISCORD', url: 'https://discord.com/', label: 'Join the community' },
        ],
      },
      roadmapItems: {
        create: [
          { title: 'Vertical slice', status: 'DONE', position: 0 },
          { title: 'Demo for Next Fest', status: 'IN_PROGRESS', position: 1 },
          { title: 'Full soundtrack', status: 'PLANNED', position: 2 },
        ],
      },
    },
  });

  await prisma.devlog.upsert({
    where: { gameId_slug: { gameId: game.id, slug: 'hello-lanternfall' } },
    update: {},
    create: {
      gameId: game.id,
      authorId: dev.id,
      title: 'Hello, Lanternfall',
      slug: 'hello-lanternfall',
      body: 'This is the very first devlog. We are building in public — follow along!',
      isPublished: true,
      publishedAt: new Date(),
    },
  });

  await prisma.pressKit.upsert({
    where: { gameId: game.id },
    update: {},
    create: {
      gameId: game.id,
      headline: 'Lanternfall — press kit',
      contactEmail: 'press@aurora.example',
      isAutoGenerated: true,
      factSheet: {
        developer: 'Aurora Works',
        basedIn: 'Lisbon, Portugal',
        releaseWindow: 'Q4 2026',
        platforms: ['PC'],
      },
    },
  });

  console.log('✅  Seed complete.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
